server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - predicates:
            - Path=/zcf/**
          filters:
            - StripPrefix=1
          uri: http://localhost:8081
  zipkin:
    base-url: http://192.168.1.200:9411
  sleuth:
    sampler:
      probability: 1


